# Generated by Django 5.0.1 on 2024-01-25 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textclassifier', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
